import java.util.Random;

public class MastermindColorSequence
{
    int[] fColorSequence;
    int[] fGuessAnalysis = {9, 9, 9, 9};

    public MastermindColorSequence()
    {
        fColorSequence = new int[4];
    }

    /**
     * Sets the color sequence to a random color sequence.
     */
    public void generateRandomColorSequence()
    {
        Random random = new Random();

        for(int i = 0; i < 4; i++)
        {
            fColorSequence[i] = random.nextInt(5) + 1;
        }
    }

    /**
     * Sets the instance sequence to the color sequence.
     * @param colorSequence The color sequence the instance sequence will be set to.
     */
    public void setColorSequence(int[] colorSequence)
    {
        fColorSequence = colorSequence;
    }

    /**
     * Gets the color sequence
     * @return An int array representing the color sequence.
     */
    public int[] getColorSequence()
    {
        return fColorSequence;
    }

    public int[] getGuessAnalysis()
    {
        return fGuessAnalysis;
    }

    /**
     * Resets the color sequence list so that all of the colors are 0
     */
    public void resetColorSequence()
    {
        fColorSequence = new int[4];
    }

    /**
     * Changes a color at a specific point in the sequence.
     * @param index The index at which the list is being set to the color value.
     * @param color The color being changed to.
     */
    public void setColors(int index, int color)
    {
        fColorSequence[index] = color;
    }

    /**
     * Compares the user's color sequence guess to the correct computer generated sequence.
     *
     * @param computerSequence The color sequence generated by the computer.
     * @return An int array representing the comparison between the correct color sequence and guessed color sequence.
     * 7 indicates that a color is in the sequence and that the color is in the correct position.
     * 8 indicates that a color is in the sequence but not in the correct position.
     * 9 indicates that no color is in the sequence.
     */
    public int[] checkGuess(int[] computerSequence)
    {

        //sets ints in guessAnalysis to 7 or 8 based on the comparison
        for(int i = 0; i < fColorSequence.length; i++)                  //iterate across the guessed sequence
        {
            for(int j = computerSequence.length - 1; j >= 0; j--)       //iterate down the correct sequence for each color in the guessed sequence
            {
                if(fColorSequence[i] == computerSequence[i])            //colors are the same
                {
                    if(i == j)                                          //colors are in the same position
                    {
                        fGuessAnalysis[i] = 7;
                        break;                                          //closes the inner loop so that the value is not reset to 8 if the
                    }                                                   //same color is found in a different position
                    else                                                //same colors but different position
                    {
                        fGuessAnalysis[i] = 8;
                    }
                }
            }
        }

        //selection sort from least to greatest
        for (int i = 0; i < fGuessAnalysis.length - 1; i++)
        {
            int index = i;
            for (int j = i + 1; j < fGuessAnalysis.length; j++)
                if (fGuessAnalysis[j] < fGuessAnalysis[index])
                    index = j;

            int smallerNumber = fGuessAnalysis[index];
            fGuessAnalysis[index] = fGuessAnalysis[i];
            fGuessAnalysis[i] = smallerNumber;
        }

        boolean hasWon = true;
        //Checks to see if the guess matches the computer sequence
        for(int num: fGuessAnalysis)
        {
            if(num != 7)
            {
                hasWon = false;
            }
        }

        if(hasWon)
        {
            return null;
        }

        return fGuessAnalysis;
    }
}
